[package]
name = "network-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0"
chrono = "0.4"
dns-lookup = "1.0.8"
socket2 = "0.4.4"
