[package]
name = "network-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0"
chrono = "0.4"
get_if_addrs = "0.5.3"
ureq = "2.4.0"
